---
- name: Check if file exist copy it and then delete
  hosts: all
  vars:
    mysrc: "~/foo"
    mydst: "~/bar"
  tasks:
    - name: check if file exists
      ansible.builtin.stat:
        path: "{{ mysrc }}"
      register: check_file_name

    - name: print debug
      ansible.builtin.debug:
        var: check_file_name

    - name: copy file with new name
      ansible.builtin.copy:
        remote_src: true
        src: "{{ mysrc }}"
        dest: "{{ mydst }}"
      when: check_file_name.stat.exists

    - name: remove odl file
      ansible.builtin.file:
        path: "{{ mysrc}}"
        state: absent
      when: check_file_name.stat.exists
