---
- name: test pulling a per-device password from Cyberark AIM
  hosts: '{{ inventory_hostname | default("localhost") }}'
  gather_facts: false

  vars:
    ca_base_url: "https://url-cyberark-aim"
  

  tasks:
    - name: Retrieve password from Cyberark
      cyberark.pas.cyberark_credential:
        api_base_url: "{{ ca_base_url }}"
        app_id: "API-TEST-AWX"
        query: "safe=CYBERARK_SAFE_NALE;UserName=USER_NAME;Object={{ inventory_hostname.split('.')[0] | upper }}-USER_NAME"
        validate_certs: no
        fail_request_on_password_change: true
        connection_timeout: 60
      run_once: false
      register: ca_password

    - name: show retrieved password
      ansible.builtin.debug:
        var: ca_password.result.content  
      
    - name: set connection vars dynamically
      ansible.builtin.set_fact:
         ansible_user: USER_NAME
         ansible_password: "{{ ca_password.result.content }}"
         ansible_port: 22
  
    - name: show connected user
      ansible.builtin.command: whoami
      register: whoami_out

    - name: Show result
      debug:
        msg: "Connected as {{ whoami_out.stdout }} on {{ inventory_hostname }}"

    - name: Get OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_out

    - name: Display OS
      debug:
        var: os_out.stdout
