---
- name: facts
  hosts: all
  tasks:

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: print a specifiq message
      ansible.builtin.debug:
        msg: I'm conneection to {{ ansible_facts['hostname'] }} 
             where {{ ansible_facts['os_family'] }} operating system is installed      
