---
- name: fetch file from remote
  hosts: all
  become: true
  vars:
    log_file: "/var/log/messages"
    dump_dir: "logs"
  vars_files:
    - vault.yml    
  tasks: 
    - name: lets fecth log from our servers
      ansible.builtin.fetch:
        src: "{{ log_file }}"
        dest: "{{ dump_dir }}"
      when: ansible_facts['distribution'] == "CentOS"
