---
- name: Fetch and Copy File between Hosts
  hosts: linux
  gather_facts: yes
  tasks:

    - name : get date timestamp
      ansible.builtin.command: date +%Y%m%d
      register: datetime

    - name: Fetch the FILE_TEST_{{ datetime.stdout }} from the awx-client1 to master
      run_once: yes
      ansible.builtin.fetch: 
        src=/tmp/FILE_TEST_{{ datetime.stdout }} 
        dest=buffer/ flat=yes
      when: inventory_hostname == 'awx-client1'

    - name: Copy the FILE_TEST_{{ datetime.stdout }} from master to awx-client2
      ansible.builtin.copy: 
        src=buffer/FILE_TEST_{{ datetime.stdout }} 
        dest=/tmp/
      when: inventory_hostname == 'awx-client2'
