---
- name: Fetch and Copy File between Hosts
  hosts: all
  gather_facts: no
  tasks:
    - name : get date timestamp
      command: date +%Y%m%d
      register: datetime
      
    - name: Fetch the file from the awx-client1 to master
      run_once: yes
      fetch: src=/tmp/FILE_TEST_{{ datetime.stdout }} dest=buffer/ flat=yes
      when: "{{ ansible_hostname == 'awx-client1' }}"

    - name: Copy the file from master to awx-client2
      copy: src=buffer/FILE_TEST_{{ datetime.stdout }} dest=/tmp/
      when: "{{ ansible_hostname == 'awx-client2' }}"