---
- name: configure motd
  hosts: all
  become: true
  vars_files:
    - vault.yml
  tasks:
    - name: configure the message of the day 
      ansible.builtin.copy:
        content: "Welcome to {{ item }} Linux" 
        dest: /etc/motd
      notify: MOTD changed
      with_items: ['CentOS', 'Debian']
      when: ansible_distribution == item

  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed

