---
- name: Perform Windows updates
  hosts: windows
  gather_facts: false
  become: true
  vars_prompt:
    - name: "ansible_ssh_pass"
      prompt: Windows password
      private: true

  tasks:
    - name: Update the Windows server
      ansible.windows.win_updates:
        category_names:
        #  - SecurityUpdates
          - CriticalUpdates
        #  - DefiitionUpdate
        #  - UpdatesRollups
        #  - FeaturesPacks
        #  - ServicesPacks
        #  - UpdatesRollups
        #  - Updates
        state: searched
        reboot: yes
        reboot_timeout: 3600
      register: update_output

    - name: Print out the results
      ansible.builtin.debug:
        var: update_output
